export enum Skill {
   AGILE = 'Agile Methods',
   ALGO_PROG = 'Algorithms and Programming',
   ANGULAR = 'Angular',
   API_PLATFORM = 'API Platform',
   BLENDER = 'Blender',
   COM = 'Team Communication',
   CPP = 'C++',
   CSS = 'CSS',
   C_SHARP = 'C#',
   DEV_WEB = 'Web Development',
   DOCKER = 'Docker',
   EXPRESS = 'Express',
   FLUTTER = 'Flutter',
   GAME_DESIGN = 'Game Design',
   GESTION_PROJ = 'Project Management',
   GIMP = 'GIMP',
   GIT = 'Git',
   GITLAB = 'GitLab',
   HLSL = 'HLSL',
   HTML = 'HTML',
   IA = 'Artificial Intelligence',
   ISTANBUL = 'Istanbul',
   JAVASCRIPT = 'JavaScript',
   JAVA = 'Java',
   JEST = 'Jest',
   KANBAN = 'Kanban',
   KOTLIN = 'Kotlin',
   MOCHA = 'Mocha',
   MVI = 'MVI',
   NEXT_JS = 'Next.js',
   ORS = 'Open Route Service',
   PAINT_NET = 'Paint.net',
   PHP = 'PHP',
   PHPUNIT = 'PHPUnit',
   PLASTIC_SCM = 'Plastic SCM',
   POO = 'Object-Oriented Programming',
   PYTHON = 'Python',
   QT = 'Qt',
   RAG = 'RAG',
   REACT = 'React',
   REL_CLIENT = 'Customer Relationship',
   RESOLUTION_PROB = 'Problem Solving',
   REST_API = "REST API",
   RUST = 'Rust',
   SDK_AWS = 'AWS SDK',
   SCALA = 'Scala',
   SEC = 'Security',
   SELENIUM = 'Selenium',
   SHADCN_UI = 'shadcn/ui',
   SPRING = 'Spring',
   SQL = 'SQL',
   SVELTE = 'Svelte',
   SYMFONY = 'Symfony',
   TAILWIND = 'Tailwind CSS',
   TDD = 'TDD',
   THREE_JS = 'Three.js',
   TRAV_EQUIP = 'Teamwork',
   TYPESCRIPT = 'TypeScript',
   UNITY = 'Unity',
   TOUCHDESIGNER = 'TouchDesigner',
   GRPC = 'gRPC',
   GLSL = 'GLSL',
   VUE = "Vue.js",
   HONO = "Hono",
   CLOUDFLARE_WORKERS = "Cloudflare Workers",
   CLOUDFLARE_AI = "Cloudflare AI",
   CLOUDFLARE_KV = "Cloudflare KV",
   STABLE_DIFF = "Stable Diffusion",
   JIMP = "Jimp",
   ZOD = "Zod",
   OPEN_API = "OpenAPI",
   VITE = "Vite",
}

const colorMapping: { [key in Skill]: string } = {
   [Skill.AGILE]: '#6f42c1',
   [Skill.ALGO_PROG]: '#1b4f96',
   [Skill.ANGULAR]: '#dd1b16',
   [Skill.API_PLATFORM]: '#0099A1',
   [Skill.BLENDER]: '#f5792a',
   [Skill.COM]: '#28a745',
   [Skill.CPP]: '#f34b7d',
   [Skill.CSS]: '#264EE4',
   [Skill.C_SHARP]: '#9b4f96',
   [Skill.DEV_WEB]: '#e34f26',
   [Skill.DOCKER]: '#0db7ed',
   [Skill.EXPRESS]: '#68a063',
   [Skill.FLUTTER]: '#02569b',
   [Skill.GAME_DESIGN]: '#ffa500',
   [Skill.GESTION_PROJ]: '#17a2b8',
   [Skill.GIMP]: '#5a5a5a',
   [Skill.GIT]: '#f14e32',
   [Skill.GITLAB]: '#fc6d27',
   [Skill.HLSL]: '#5a5a5a',
   [Skill.HTML]: '#e34c26',
   [Skill.IA]: '#0099ff',
   [Skill.ISTANBUL]: '#f0ad4e',
   [Skill.JAVASCRIPT]: '#f7df1e',
   [Skill.JAVA]: '#007396',
   [Skill.JEST]: '#99424f',
   [Skill.KANBAN]: '#29a329',
   [Skill.KOTLIN]: '#7f52ff',
   [Skill.MOCHA]: '#8d6748',
   [Skill.MVI]: '#6c757d',
   [Skill.NEXT_JS]: '#000000',
   [Skill.ORS]: '#b5152b',
   [Skill.PAINT_NET]: '#5a5a5a',
   [Skill.PHP]: '#777bb3',
   [Skill.PHPUNIT]: '#4F5D95',
   [Skill.PLASTIC_SCM]: '#fd7e14',
   [Skill.POO]: '#808080',
   [Skill.PYTHON]: '#306998',
   [Skill.QT]: '#41cd52',
   [Skill.RAG]: '#d9534f',
   [Skill.REACT]: '#61dafb',
   [Skill.REL_CLIENT]: '#ff4500',
   [Skill.RESOLUTION_PROB]: '#6c757d',
   [Skill.REST_API]: '#563d7c',
   [Skill.RUST]: '#dea584',
   [Skill.SDK_AWS]: '#ff9900',
   [Skill.SCALA]: '#dc322f',
   [Skill.SEC]: '#2b7a78',
   [Skill.SELENIUM]: '#43b02a',
   [Skill.SHADCN_UI]: '#000000',
   [Skill.SPRING]: '#6db33f',
   [Skill.SQL]: '#00758f',
   [Skill.SVELTE]: '#ff3e00',
   [Skill.SYMFONY]: '#000000',
   [Skill.TAILWIND]: '#38b2ac',
   [Skill.TDD]: '#4a4a4a',
   [Skill.THREE_JS]: '#000000',
   [Skill.TRAV_EQUIP]: '#17a2b8',
   [Skill.TYPESCRIPT]: '#007acc',
   [Skill.UNITY]: '#000000',
   [Skill.TOUCHDESIGNER]: '#9F49F5',
   [Skill.GRPC]: '#2da9c3',
   [Skill.GLSL]: '#5586A4',
   [Skill.VUE]: "#42b883",
   [Skill.HONO]: "#E36002",
   [Skill.CLOUDFLARE_WORKERS]: "#F48120",
   [Skill.CLOUDFLARE_AI]: "#FBAD41",
   [Skill.CLOUDFLARE_KV]: "#F6821F",
   [Skill.STABLE_DIFF]: "#9B59B6",
   [Skill.JIMP]: "#4A90D9",
   [Skill.ZOD]: "#3E67B1",
   [Skill.OPEN_API]: "#85EA2D",
   [Skill.VITE]: "#646CFF",
}

/**
 * Return the corresponding hex color for a tech, if it exists, otherwise return black.
 * @param skill
 */
export const getSkillColor = (skill: Skill): string => {
   return colorMapping[skill] || '#000000'
}