export enum Skill {
   AGILE = 'Méthodes Agiles',
   ALGO_PROG = 'Algorithmique et Programmation',
   ANGULAR = 'Angular',
   API_PLATFORM = 'API Platform',
   COM = 'Communication en équipe',
   CPP = 'C++',
   CSS = 'CSS',
   C_SHARP = 'C#',
   DEV_WEB = 'Développement Web',
   DOCKER = 'Docker',
   EXPRESS = 'Express',
   FLUTTER = 'Flutter',
   GAME_DESIGN = 'Game Design',
   GESTION_PROJ = 'Gestion de projet',
   GIMP = 'GIMP',
   GIT = 'Git',
   GITLAB = 'Gitlab',
   HLSL = 'HLSL',
   HTML = 'HTML',
   IA = 'IA',
   ISTANBUL = 'Istanbul',
   JEST = 'Jest',
   KANBAN = 'Kanban',
   MOCHA = 'Mocha',
   NEXT_JS = 'Next.js',
   ORS = 'Open Route Service',
   PAINT_NET = 'Paint.net',
   PHP = 'PHP',
   PHPUNIT = 'PHPUnit',
   PLASTIC_SCM = 'Plastic SCM',
   POO = 'POO',
   PYTHON = 'Python',
   QT = 'Qt',
   RAG = 'RAG',
   REACT = 'React',
   REL_CLIENT = 'Relation client',
   RESOLUTION_PROB = 'Résolution de problèmes',
   REST = 'REST',
   SDK_AWS = 'SDK AWS',
   SEC = 'Sécurité',
   SELENIUM = 'Selenium',
   SHADCN_UI = 'shadcn/ui',
   SQL = 'SQL',
   SYMFONY = 'Symfony',
   TAILWIND = 'Tailwind CSS',
   TDD = 'TDD',
   THREE_JS = 'Three.js',
   TRAV_EQUIP = 'Travail d’équipe',
   TYPESCRIPT = 'TypeScript',
   UNITY = 'Unity',
//   NODE = "Node JS",
//   NGINX = "NGINX"
}

const colorMapping: { [key in Skill]: string } = {
   [Skill.AGILE]: '#6f42c1',
   [Skill.ALGO_PROG]: '#1b4f96',
   [Skill.ANGULAR]: '#dd1b16',
   [Skill.API_PLATFORM]: '#0099A1',
   [Skill.COM]: '#28a745',
   [Skill.CPP]: '#f34b7d',
   [Skill.CSS]: '#264EE4',
   [Skill.C_SHARP]: '#9b4f96',
   [Skill.DEV_WEB]: '#e34f26',
   [Skill.DOCKER]: '#0db7ed',
   [Skill.EXPRESS]: '#68a063',
   [Skill.FLUTTER]: '#02569b',
   [Skill.GAME_DESIGN]: '#ffa500',
   [Skill.GESTION_PROJ]: '#17a2b8',
   [Skill.GIMP]: '#5a5a5a',
   [Skill.GIT]: '#f14e32',
   [Skill.GITLAB]: '#fc6d27',
   [Skill.HLSL]: '#5a5a5a',
   [Skill.HTML]: '#e34c26',
   [Skill.IA]: '#0099ff',
   [Skill.ISTANBUL]: '#f0ad4e',
   [Skill.JEST]: '#99424f',
   [Skill.KANBAN]: '#29a329',
   [Skill.MOCHA]: '#8d6748',
   [Skill.NEXT_JS]: '#000000',
   [Skill.ORS]: '#b5152b',
   [Skill.PAINT_NET]: '#5a5a5a',
   [Skill.PHP]: '#777bb3',
   [Skill.PHPUNIT]: '#4F5D95',
   [Skill.PLASTIC_SCM]: '#fd7e14',
   [Skill.POO]: '#808080',
   [Skill.PYTHON]: '#306998',
   [Skill.QT]: '#41cd52',
   [Skill.RAG]: '#d9534f',
   [Skill.REACT]: '#61dafb',
   [Skill.REL_CLIENT]: '#ff4500',
   [Skill.RESOLUTION_PROB]: '#6c757d',
   [Skill.REST]: '#563d7c',
   [Skill.SDK_AWS]: '#ff9900',
   [Skill.SEC]: '#2b7a78',
   [Skill.SELENIUM]: '#43b02a',
   [Skill.SHADCN_UI]: '#000000',
   [Skill.SQL]: '#00758f',
   [Skill.SYMFONY]: '#000000',
   [Skill.TAILWIND]: '#38b2ac',
   [Skill.TDD]: '#4a4a4a',
   [Skill.THREE_JS]: '#000000',
   [Skill.TRAV_EQUIP]: '#17a2b8',
   [Skill.TYPESCRIPT]: '#007acc',
   [Skill.UNITY]: '#000000',
}

/**
 * Return the corresponding hex color for a tech, if it exists, otherwise return black.
 * @param skill
 */
export const getSkillColor = (skill: Skill): string => {
   return colorMapping[skill] || '#000000'
}
