export enum Skill {
   AGILE = 'Agile Methods',
   ALGO_PROG = 'Algorithms and Programming',
   ANGULAR = 'Angular',
   API_PLATFORM = 'API Platform',
   BIG_DATA = 'Big Data',
   BLENDER = 'Blender',
   BUN = 'Bun',
   CLEAN_ARCHITECTURE = 'Clean Architecture',
   COM = 'Team Communication',
   CPP = 'C++',
   CSV = 'CSV',
   CSS = 'CSS',
   C_SHARP = 'C#',
   DEVOPS = 'DevOps',
   DEV_WEB = 'Web Development',
   DOCKER = 'Docker',
   EXPRESS = 'Express',
   FLUTTER = 'Flutter',
   GAME_DESIGN = 'Game Design',
   GESTION_PROJ = 'Project Management',
   GIMP = 'GIMP',
   GIT = 'Git',
   GITLAB = 'GitLab',
   GRAPHIC_DESIGN = 'Graphic Design',
   HLSL = 'HLSL',
   HTML = 'HTML',
   IA = 'Artificial Intelligence',
   ISTANBUL = 'Istanbul',
   JAVASCRIPT = 'JavaScript',
   JAVA = 'Java',
   JEST = 'Jest',
   JETPACK_COMPOSE = 'Jetpack Compose',
   KANBAN = 'Kanban',
   KOTLIN = 'Kotlin',
   LEAFLET = 'Leaflet',
   MOCHA = 'Mocha',
   MEDIAPIPE = 'MediaPipe',
   MIDI = 'MIDI',
   MULTITHREADING = 'Multithreading',
   MVI = 'MVI',
   NEXT_JS = 'Next.js',
   NEWSQL = 'NewSQL',
   NOSQL = 'NoSQL',
   ORS = 'Open Route Service',
   OPERATING_SYSTEMS = 'Operating Systems',
   PAINT_NET = 'Paint.net',
   PHP = 'PHP',
   PHPUNIT = 'PHPUnit',
   PLASTIC_SCM = 'Plastic SCM',
   POO = 'Object-Oriented Programming',
   PYTHON = 'Python',
   QT = 'Qt',
   RAG = 'RAG',
   REACT = 'React',
   REL_CLIENT = 'Customer Relationship',
   RESPONSIBLE_DIGITAL = 'Responsible Digital',
   RESOLUTION_PROB = 'Problem Solving',
   REST_API = "REST API",
   RUST = 'Rust',
   SDK_AWS = 'AWS SDK',
   SCALA = 'Scala',
   SEC = 'Security',
   SELENIUM = 'Selenium',
   SHADCN_UI = 'shadcn/ui',
   SPRING = 'Spring',
   SQL = 'SQL',
   SVELTE = 'Svelte',
   SYMFONY = 'Symfony',
   TAILWIND = 'Tailwind CSS',
   TDD = 'TDD',
   THREE_JS = 'Three.js',
   TRAV_EQUIP = 'Teamwork',
   TYPESCRIPT = 'TypeScript',
   UML = 'UML',
   UNITY = 'Unity',
   TOUCHDESIGNER = 'TouchDesigner',
   VCV_RACK = 'VCV Rack',
   GRPC = 'gRPC',
   GLSL = 'GLSL',
   VUE = "Vue.js",
   HONO = "Hono",
   CLOUDFLARE_WORKERS = "Cloudflare Workers",
   CLOUDFLARE_AI = "Cloudflare AI",
   CLOUDFLARE_KV = "Cloudflare KV",
   STABLE_DIFF = "Stable Diffusion",
   JIMP = "Jimp",
   ZOD = "Zod",
   OPEN_API = "OpenAPI",
   VITE = "Vite",
   GRAPHQL = "GraphQL",
   MAPBOX = 'Mapbox',
   OPENSTREETMAP = 'OpenStreetMap',
   OPENROUTESERVICE = 'OpenRouteService',
   WEBSOCKET = 'WebSocket',
   AIS = 'AIS',
   FLICKR_API = 'Flickr API',
   GSAP = 'GSAP',
   DJANGO = "Django",
   FLASK = "Flask",
   MICROSERVICES = "Microservices",
   DISTRIBUTED_SYSTEMS = "Distributed Systems",
   MATPLOTLIB = "Matplotlib",
   NUMPY = "NumPy",
   SUPABASE = "Supabase",
   POSTGRESQL = "PostgreSQL",
   NEXT_INTL = "next-intl",
   RECHARTS = "Recharts",
   RADIX_UI = "Radix UI",
   VERCEL = "Vercel",
   VERCEL_BLOB = 'Vercel Blob',
   VERCEL_ANALYTICS = "Vercel Analytics",
   FRAMER_MOTION = "Framer Motion",
   DATE_FNS = "date-fns",
   LUCIDE = "Lucide Icons",
   OPEN_LIBRARY_API = "Open Library API",
   APP_ROUTER = "Next.js App Router",
   SERVER_ACTIONS = "Next.js Server Actions",
   NEXT_MIDDLEWARE = "Next.js Middleware",
   SSR = "Server-Side Rendering",
   HUGGINGFACE = "Hugging Face",
   CHROMADB = "ChromaDB",
   LANGCHAIN = "LangChain",
}

const colorMapping: { [key in Skill]: string } = {
   [Skill.AGILE]: '#6f42c1',
   [Skill.ALGO_PROG]: '#1b4f96',
   [Skill.ANGULAR]: '#dd1b16',
   [Skill.API_PLATFORM]: '#0099A1',
   [Skill.BIG_DATA]: '#7C3AED',
   [Skill.BLENDER]: '#f5792a',
   [Skill.BUN]: '#F6A623',
   [Skill.CLEAN_ARCHITECTURE]: '#0F766E',
   [Skill.COM]: '#28a745',
   [Skill.CPP]: '#f34b7d',
   [Skill.CSV]: '#16A34A',
   [Skill.CSS]: '#264EE4',
   [Skill.C_SHARP]: '#9b4f96',
   [Skill.DEVOPS]: '#2563EB',
   [Skill.DEV_WEB]: '#e34f26',
   [Skill.DOCKER]: '#0db7ed',
   [Skill.EXPRESS]: '#68a063',
   [Skill.FLUTTER]: '#02569b',
   [Skill.GAME_DESIGN]: '#ffa500',
   [Skill.GESTION_PROJ]: '#17a2b8',
   [Skill.GIMP]: '#5a5a5a',
   [Skill.GIT]: '#f14e32',
   [Skill.GITLAB]: '#fc6d27',
   [Skill.GRAPHIC_DESIGN]: '#DB2777',
   [Skill.HLSL]: '#5a5a5a',
   [Skill.HTML]: '#e34c26',
   [Skill.IA]: '#0099ff',
   [Skill.ISTANBUL]: '#f0ad4e',
   [Skill.JAVASCRIPT]: '#f7df1e',
   [Skill.JAVA]: '#007396',
   [Skill.JEST]: '#99424f',
   [Skill.JETPACK_COMPOSE]: '#3DDC84',
   [Skill.KANBAN]: '#29a329',
   [Skill.KOTLIN]: '#7f52ff',
   [Skill.LEAFLET]: '#199900',
   [Skill.MOCHA]: '#8d6748',
   [Skill.MEDIAPIPE]: '#FF6F00',
   [Skill.MIDI]: '#22C55E',
   [Skill.MULTITHREADING]: '#0EA5E9',
   [Skill.MVI]: '#6c757d',
   [Skill.NEXT_JS]: '#000000',
   [Skill.NEWSQL]: '#9333EA',
   [Skill.NOSQL]: '#F59E0B',
   [Skill.ORS]: '#b5152b',
   [Skill.OPERATING_SYSTEMS]: '#475569',
   [Skill.PAINT_NET]: '#5a5a5a',
   [Skill.PHP]: '#777bb3',
   [Skill.PHPUNIT]: '#4F5D95',
   [Skill.PLASTIC_SCM]: '#fd7e14',
   [Skill.POO]: '#808080',
   [Skill.PYTHON]: '#306998',
   [Skill.QT]: '#41cd52',
   [Skill.RAG]: '#d9534f',
   [Skill.REACT]: '#61dafb',
   [Skill.REL_CLIENT]: '#ff4500',
   [Skill.RESPONSIBLE_DIGITAL]: '#0D9488',
   [Skill.RESOLUTION_PROB]: '#6c757d',
   [Skill.REST_API]: '#563d7c',
   [Skill.RUST]: '#dea584',
   [Skill.SDK_AWS]: '#ff9900',
   [Skill.SCALA]: '#dc322f',
   [Skill.SEC]: '#2b7a78',
   [Skill.SELENIUM]: '#43b02a',
   [Skill.SHADCN_UI]: '#000000',
   [Skill.SPRING]: '#6db33f',
   [Skill.SQL]: '#00758f',
   [Skill.SVELTE]: '#ff3e00',
   [Skill.SYMFONY]: '#000000',
   [Skill.TAILWIND]: '#38b2ac',
   [Skill.TDD]: '#4a4a4a',
   [Skill.THREE_JS]: '#000000',
   [Skill.TRAV_EQUIP]: '#17a2b8',
   [Skill.TYPESCRIPT]: '#007acc',
   [Skill.UML]: '#6366F1',
   [Skill.UNITY]: '#000000',
   [Skill.TOUCHDESIGNER]: '#9F49F5',
   [Skill.VCV_RACK]: '#111827',
   [Skill.GRPC]: '#2da9c3',
   [Skill.GLSL]: '#5586A4',
   [Skill.VUE]: "#42b883",
   [Skill.HONO]: "#E36002",
   [Skill.CLOUDFLARE_WORKERS]: "#F48120",
   [Skill.CLOUDFLARE_AI]: "#FBAD41",
   [Skill.CLOUDFLARE_KV]: "#F6821F",
   [Skill.STABLE_DIFF]: "#9B59B6",
   [Skill.JIMP]: "#4A90D9",
   [Skill.ZOD]: "#3E67B1",
   [Skill.OPEN_API]: "#85EA2D",
   [Skill.VITE]: "#646CFF",
   [Skill.GRAPHQL]: "#E10098",
   [Skill.MAPBOX]: '#4264FB',
   [Skill.OPENSTREETMAP]: '#7EBC6F',
   [Skill.OPENROUTESERVICE]: '#1D4ED8',
   [Skill.WEBSOCKET]: '#0EA5E9',
   [Skill.AIS]: '#0F766E',
   [Skill.FLICKR_API]: '#FF0084',
   [Skill.GSAP]: '#88CE02',
   [Skill.DJANGO]: "#092E20",
   [Skill.FLASK]: "#000000",
   [Skill.MICROSERVICES]: "#0066CC",
   [Skill.DISTRIBUTED_SYSTEMS]: "#FF6B6B",
   [Skill.MATPLOTLIB]: "#11557C",
   [Skill.NUMPY]: "#4D77CF",
   [Skill.SUPABASE]: "#3ECF8E",
   [Skill.POSTGRESQL]: "#336791",
   [Skill.NEXT_INTL]: "#0EA5E9",
   [Skill.RECHARTS]: "#FF7300",
   [Skill.RADIX_UI]: "#111111",
   [Skill.VERCEL]: "#000000",
   [Skill.VERCEL_BLOB]: '#6B7280',
   [Skill.VERCEL_ANALYTICS]: "#1F2937",
   [Skill.FRAMER_MOTION]: "#0055FF",
   [Skill.DATE_FNS]: "#D97706",
   [Skill.LUCIDE]: "#F97316",
   [Skill.OPEN_LIBRARY_API]: "#E44C30",
   [Skill.APP_ROUTER]: "#111827",
   [Skill.SERVER_ACTIONS]: "#14B8A6",
   [Skill.NEXT_MIDDLEWARE]: "#8B5CF6",
   [Skill.SSR]: "#2563EB",
   [Skill.HUGGINGFACE]: "#FFD21E",
   [Skill.CHROMADB]: "#FFFFFF",
   [Skill.LANGCHAIN]: "#1C3144",
}

/**
 * Return the corresponding hex color for a tech, if it exists, otherwise return black.
 * @param skill
 */
export const getSkillColor = (skill: Skill): string => {
   return colorMapping[skill] || '#000000'
}